//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public string Name { get; set; }
        public Nullable<int> Int { get; set; }
        public Nullable<long> BigInt { get; set; }
        public Nullable<bool> Bit { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Text { get; set; }
    }
}
