//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int UserId { get; set; }
        public int ContactId { get; set; }
        public System.DateTime When { get; set; }
        public byte Source { get; set; }
    
        public virtual SourceFeature SourceFeature { get; set; }
        public virtual User ContactUser { get; set; }
        public virtual User User { get; set; }
    }
}
