//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextChat
    {
        public long ID { get; set; }
        public System.DateTime When { get; set; }
        public string RoomId { get; set; }
        public Nullable<int> UserId { get; set; }
        public long DeviceTag { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Text { get; set; }
        public byte Visibility { get; set; }
    
        public virtual MessageVisibilityType MessageVisibilityType { get; set; }
        public virtual User User { get; set; }
    }
}
