//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextChatTracker
    {
        public int UserId { get; set; }
        public string RoomId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public byte Status { get; set; }
        public System.DateTime StatusAt { get; set; }
        public bool Initiator { get; set; }
    
        public virtual TextChatTrackerStatus TrackerStatus { get; set; }
        public virtual User User { get; set; }
        public virtual User Partner { get; set; }
    }
}
