//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TilesFiltering
    {
        public int UserId { get; set; }
        public int TileId { get; set; }
        public byte FilterId { get; set; }
    
        public virtual TilesFilter TilesFilter { get; set; }
        public virtual User User { get; set; }
    }
}
