//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.MailsFrom = new HashSet<Mail>();
            this.MailsTo = new HashSet<Mail>();
            this.UsersChanges = new HashSet<UsersChanges>();
            this.TextChats = new HashSet<TextChat>();
            this.VoiceCaller = new HashSet<VoiceCall>();
            this.VoiceCallee = new HashSet<VoiceCall>();
            this.TilesFilterings = new HashSet<TilesFiltering>();
            this.ContactsContactIds = new HashSet<Contact>();
            this.ContactsUserIds = new HashSet<Contact>();
            this.UsersDevices = new HashSet<UsersDevice>();
            this.Tags = new HashSet<UsersTagsValue>();
            this.UserChatTrackers = new HashSet<TextChatTracker>();
            this.PartnerChatTrackers = new HashSet<TextChatTracker>();
            this.Notifies = new HashSet<Notify>();
            this.MailsArchives = new HashSet<MailsArchive>();
            this.MailsArchives1 = new HashSet<MailsArchive>();
        }
    
        public int Id { get; set; }
        public System.DateTime Since { get; set; }
        public byte StatusId { get; set; }
        public bool Listed { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public int BirthYear { get; set; }
        public byte BirthMonth { get; set; }
        public byte CountryId { get; set; }
        public string Location { get; set; }
        public byte KnowsId { get; set; }
        public Nullable<byte> Knows2Id { get; set; }
        public Nullable<byte> Knows3Id { get; set; }
        public byte LearnsId { get; set; }
        public Nullable<byte> Learns2Id { get; set; }
        public Nullable<byte> Learns3Id { get; set; }
        public string Introduction { get; set; }
        public string AspNetId { get; set; }
        public bool Banned { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Country Country { get; set; }
        public virtual Language Knows { get; set; }
        public virtual Language Knows2 { get; set; }
        public virtual Language Knows3 { get; set; }
        public virtual Language Learns { get; set; }
        public virtual Language Learns2 { get; set; }
        public virtual Language Learns3 { get; set; }
        public virtual UsersStatus Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mail> MailsFrom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mail> MailsTo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersChanges> UsersChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TextChat> TextChats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoiceCall> VoiceCaller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoiceCall> VoiceCallee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TilesFiltering> TilesFilterings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> ContactsContactIds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> ContactsUserIds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersDevice> UsersDevices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersTagsValue> Tags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TextChatTracker> UserChatTrackers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TextChatTracker> PartnerChatTrackers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notify> Notifies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailsArchive> MailsArchives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailsArchive> MailsArchives1 { get; set; }
    }
}
