//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersChanges
    {
        public long Id { get; set; }
        public byte ChangeType { get; set; }
        public Nullable<int> DeviceTag { get; set; }
        public string Email { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> BirthYear { get; set; }
        public Nullable<byte> BirthMonth { get; set; }
        public Nullable<byte> Country { get; set; }
        public string Location { get; set; }
        public Nullable<byte> KnowsId { get; set; }
        public Nullable<byte> Knows2Id { get; set; }
        public Nullable<byte> Knows3Id { get; set; }
        public Nullable<byte> LearnsId { get; set; }
        public Nullable<byte> Learns2Id { get; set; }
        public Nullable<byte> Learns3Id { get; set; }
        public string Introduction { get; set; }
        public System.DateTime When { get; set; }
    
        public virtual Country Country1 { get; set; }
        public virtual Language Knows { get; set; }
        public virtual Language Knows2 { get; set; }
        public virtual Language Knows3 { get; set; }
        public virtual Language Learns { get; set; }
        public virtual Language Learns2 { get; set; }
        public virtual Language Learns3 { get; set; }
        public virtual User User { get; set; }
        public virtual UsersChanges UsersChanges1 { get; set; }
        public virtual UsersChanges UsersChanx1 { get; set; }
        public virtual UsersChangesType UsersChangesType { get; set; }
    }
}
