//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoicePlatform
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VoicePlatform()
        {
            this.VoiceCalls = new HashSet<VoiceCall>();
        }
    
        public byte Id { get; set; }
        public string PlatformName { get; set; }
        public string PlatformText { get; set; }
        public bool ThirdParty { get; set; }
        public string ContactIdNaming { get; set; }
        public string ContactIdRegex { get; set; }
        public string RgbColor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VoiceCall> VoiceCalls { get; set; }
    }
}
