//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoiceCall
    {
        public long Id { get; set; }
        public System.DateTime Created { get; set; }
        public byte Source { get; set; }
        public int CallerId { get; set; }
        public int CalleeId { get; set; }
        public Nullable<byte> Platform { get; set; }
        public Nullable<System.DateTime> Accepted { get; set; }
        public Nullable<byte> Outcome { get; set; }
        public Nullable<System.DateTime> Ended { get; set; }
    
        public virtual SourceFeature SourceFeature { get; set; }
        public virtual User UserCaller { get; set; }
        public virtual User UserCallee { get; set; }
        public virtual VoiceCallOutcome VoiceCallOutcome { get; set; }
        public virtual VoicePlatform VoicePlatform { get; set; }
    }
}
