//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _unused {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _unused() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Considerate.Hellolingo.I18N._unused", typeof(_unused).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your partner has left..
        /// </summary>
        internal static string Audio_Peer_Disconnected {
            get {
                return ResourceManager.GetString("Audio_Peer_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string ChatHistoryTitle {
            get {
                return ResourceManager.GetString("ChatHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Members.
        /// </summary>
        internal static string IdleMembers {
            get {
                return ResourceManager.GetString("IdleMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitations to chat.
        /// </summary>
        internal static string InvitationsToChat {
            get {
                return ResourceManager.GetString("InvitationsToChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed Invitations.
        /// </summary>
        internal static string MissedInvitations {
            get {
                return ResourceManager.GetString("MissedInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add more languages later.
        /// </summary>
        internal static string MoreLangsLater {
            get {
                return ResourceManager.GetString("MoreLangsLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat in Chinese.
        /// </summary>
        internal static string PageTitle_TextChatRoomChinese {
            get {
                return ResourceManager.GetString("PageTitle_TextChatRoomChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Language Chat.
        /// </summary>
        internal static string PageTitle_TextChatRoomEnglish {
            get {
                return ResourceManager.GetString("PageTitle_TextChatRoomEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Language Chat.
        /// </summary>
        internal static string PageTitle_TextChatRoomFrench {
            get {
                return ResourceManager.GetString("PageTitle_TextChatRoomFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German Language Chat.
        /// </summary>
        internal static string PageTitle_TextChatRoomGerman {
            get {
                return ResourceManager.GetString("PageTitle_TextChatRoomGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hellolingo Chat.
        /// </summary>
        internal static string PageTitle_TextChatRoomHelloLingo {
            get {
                return ResourceManager.GetString("PageTitle_TextChatRoomHelloLingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian Language Chat.
        /// </summary>
        internal static string PageTitle_TextChatRoomItalian {
            get {
                return ResourceManager.GetString("PageTitle_TextChatRoomItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese Language Chat.
        /// </summary>
        internal static string PageTitle_TextChatRoomJapanese {
            get {
                return ResourceManager.GetString("PageTitle_TextChatRoomJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean Language Chat.
        /// </summary>
        internal static string PageTitle_TextChatRoomKorean {
            get {
                return ResourceManager.GetString("PageTitle_TextChatRoomKorean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiLanguage Chat.
        /// </summary>
        internal static string PageTitle_TextChatRoomMulti {
            get {
                return ResourceManager.GetString("PageTitle_TextChatRoomMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese Language Chat.
        /// </summary>
        internal static string PageTitle_TextChatRoomPortuguese {
            get {
                return ResourceManager.GetString("PageTitle_TextChatRoomPortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian Language Chat.
        /// </summary>
        internal static string PageTitle_TextChatRoomRussian {
            get {
                return ResourceManager.GetString("PageTitle_TextChatRoomRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish Language Chat.
        /// </summary>
        internal static string PageTitle_TextChatRoomSpanish {
            get {
                return ResourceManager.GetString("PageTitle_TextChatRoomSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An App for your Windows Phone.
        /// </summary>
        internal static string WindowsPhoneAppDescription {
            get {
                return ResourceManager.GetString("WindowsPhoneAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Windows phone.
        /// </summary>
        internal static string WindowsPhoneAppTitle {
            get {
                return ResourceManager.GetString("WindowsPhoneAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your partner is online.
        /// </summary>
        internal static string YourPartnerIsOnline {
            get {
                return ResourceManager.GetString("YourPartnerIsOnline", resourceCulture);
            }
        }
    }
}
