//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeadSiteLandingResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeadSiteLandingResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Considerate.Hellolingo.I18N.DeadSiteLandingResource", typeof(DeadSiteLandingResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After a decade and millions of members, this vibrant community&lt;br&gt;of language learners has simply been... discarded!.
        /// </summary>
        public static string AfterADecadeLivemochaDiscardedMsg {
            get {
                return ResourceManager.GetString("AfterADecadeLivemochaDiscardedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 10 years and over 1.6 million members, this vibrant&lt;br&gt;community of language learners has simply been... discarded!.
        /// </summary>
        public static string AfterADecadeSharedTalkDiscardedMsg {
            get {
                return ResourceManager.GetString("AfterADecadeSharedTalkDiscardedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ready for&lt;br&gt;a new community?.
        /// </summary>
        public static string AreYouReadyForANewCommunity {
            get {
                return ResourceManager.GetString("AreYouReadyForANewCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *built by the original &lt;a href=&quot;http://www.linkedin.com/in/bernardvanderydt&quot; target=&quot;_blank&quot;&gt;founder&lt;/a&gt; of SharedTalk.
        /// </summary>
        public static string BuiltByFoundOfSharedTalk {
            get {
                return ResourceManager.GetString("BuiltByFoundOfSharedTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get your Hellolingo account now!.
        /// </summary>
        public static string GetYourHellolingoAccountNow {
            get {
                return ResourceManager.GetString("GetYourHellolingoAccountNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;&lt;a href=&quot;http://www.livemocha.com&quot; target=&quot;_blank&quot;&gt;Livemocha&lt;/a&gt; closed&lt;/span&gt;&lt;br&gt;permanently on April 22, 2016!.
        /// </summary>
        public static string LivemochaClosedOnApril2016 {
            get {
                return ResourceManager.GetString("LivemochaClosedOnApril2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;SharedLingo and Hellolingo&lt;/span&gt;&lt;br&gt;join theirs forces!.
        /// </summary>
        public static string SharedLingoJoinsHellolingo {
            get {
                return ResourceManager.GetString("SharedLingoJoinsHellolingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;&lt;a href=&quot;https://www.quora.com/Why-is-Sharedtalk-closing-down&quot; target=&quot;_blank&quot;&gt;SharedTalk&lt;/a&gt; closed&lt;/span&gt;&lt;br&gt;permanently on September 1st, 2015!.
        /// </summary>
        public static string SharedTalkClosedOnApril2016 {
            get {
                return ResourceManager.GetString("SharedTalkClosedOnApril2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Together, SharedLingo and Hellolingo will better serve a growing community of language learners. We keep our goals to be entirely free and always present for you to connect with your preferred language partners..
        /// </summary>
        public static string TogetherSLAndHL {
            get {
                return ResourceManager.GetString("TogetherSLAndHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We think you deserve better!.
        /// </summary>
        public static string WeThinkYouDeserveBetter {
            get {
                return ResourceManager.GetString("WeThinkYouDeserveBetter", resourceCulture);
            }
        }
    }
}
