//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Considerate.Hellolingo.I18N.EmailResources", typeof(EmailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you cannot view this email properly, please #OpenLink#click here#CloseLink#.
        /// </summary>
        public static string CantSeeEmail {
            get {
                return ResourceManager.GetString("CantSeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open your Hellolingo mailbox..
        /// </summary>
        public static string NotificationLinkToMailbox {
            get {
                return ResourceManager.GetString("NotificationLinkToMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view it..
        /// </summary>
        public static string NotificationLinkToVoiceOut {
            get {
                return ResourceManager.GetString("NotificationLinkToVoiceOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve got mail from &lt;B&gt;#SenderFullName#&lt;/B&gt;!.
        /// </summary>
        public static string NotificationMessage {
            get {
                return ResourceManager.GetString("NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from #SenderFullName# - Hellolingo.
        /// </summary>
        public static string NotificationSubject {
            get {
                return ResourceManager.GetString("NotificationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;#CallbackUrl#&quot;&gt;Click here to reset your Hellolingo password&lt;/a&gt;.
        /// </summary>
        public static string ResetPasswordBody {
            get {
                return ResourceManager.GetString("ResetPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve received a voice chat invitation from &lt;B&gt;#SenderFullName#&lt;/B&gt;!.
        /// </summary>
        public static string VoiceInviteMessage {
            get {
                return ResourceManager.GetString("VoiceInviteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice chat invitation from #SenderFullName# - Hellolingo.
        /// </summary>
        public static string VoiceInviteSubject {
            get {
                return ResourceManager.GetString("VoiceInviteSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Inactive Account.
        /// </summary>
        public static string WakeUpEmailSubject {
            get {
                return ResourceManager.GetString("WakeUpEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===============================================================
        ///=== HELLOLINGO\n
        ///===============================================================
        ///
        ///
        ///Hi #FirstName#
        ///
        ///
        ///This is an important message regarding your Hellolingo account. Due to inactivity, your account has been disabled and will be removed in the near future.
        ///
        ///Click here to prevent this from happening: https://www.hellolingo.com/mailbox/user/1/
        ///
        ///#BestRegards#
        ///
        ///
        ///---------------------------------------------------------------
        ///#Copyright [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WakeUpEmailTextBody {
            get {
                return ResourceManager.GetString("WakeUpEmailTextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;HTML&gt;&lt;HEAD&gt;&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;&lt;/HEAD&gt;
        ///&lt;BODY&gt;
        ///&lt;TABLE width=600 style=&quot;text-align:left; font-family:Arial, Helvetica;font-size:13&quot;&gt;
        /// &lt;TR&gt;&lt;TD height=&quot;1&quot; style=&quot;border:none; text-align:left&quot;&gt;
        ///  &lt;a href=&quot;https://www.hellolingo.com/mailbox/user/1/&quot;&gt;&lt;img src=&quot;http://www.hellolingo.com/Images/Emails/banner-blank-600-red.png&quot; width=&quot;600&quot; height=&quot;98&quot; style=&quot;border-width:0px; vertical-align:middle;&quot; /&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WakeUpHtmlBody {
            get {
                return ResourceManager.GetString("WakeUpHtmlBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for coming back to Hellolingo.com!
        ///
        ///You&apos;ve been inactive on Hellolingo recently. Please note we close inactive accounts on a regular basis. If you want to keep your account on Hellolingo, make sure you visit us frequently.
        ///
        ///Since 2016, Hellolingo has attracted more than 100,000 members from all around the world. Together, they exchange, practice and improve in more than 100 languages.
        ///
        ///Use the search feature to discover new partners and send messages. Visit the chat rooms, practice your foreign [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WakeUpMessageBody {
            get {
                return ResourceManager.GetString("WakeUpMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Inactive Account ~ Hellolingo Team ✔.
        /// </summary>
        public static string WakeUpMessageSubject {
            get {
                return ResourceManager.GetString("WakeUpMessageSubject", resourceCulture);
            }
        }
    }
}
