//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FeatureInYourLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FeatureInYourLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Considerate.Hellolingo.I18N.FeatureInYourLang", typeof(FeatureInYourLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hellolingo members are actively contributing to the community. They provide ideas, test new features and help newcomers..
        /// </summary>
        public static string ActivelyContributing {
            get {
                return ResourceManager.GetString("ActivelyContributing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... and many more..
        /// </summary>
        public static string AndManyMore {
            get {
                return ResourceManager.GetString("AndManyMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You too can contribute!.
        /// </summary>
        public static string ContributeToo {
            get {
                return ResourceManager.GetString("ContributeToo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you notice parts of Hellolingo that aren&apos;t yet fully translated in your native language and you want to complete them, {0}please contact us here{1}..
        /// </summary>
        public static string ContributeTooInfo {
            get {
                return ResourceManager.GetString("ContributeTooInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In your language!.
        /// </summary>
        public static string InYourLanguage {
            get {
                return ResourceManager.GetString("InYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many thanks to ....
        /// </summary>
        public static string ManyThanksTo {
            get {
                return ResourceManager.GetString("ManyThanksTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members have translated Hellolingo to these languages:.
        /// </summary>
        public static string MembersHaveTranslated {
            get {
                return ResourceManager.GetString("MembersHaveTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to our members, Hellolingo is available all around the world in many languages..
        /// </summary>
        public static string ThanksToThem {
            get {
                return ResourceManager.GetString("ThanksToThem", resourceCulture);
            }
        }
    }
}
