//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Considerate.Hellolingo.I18N.MainStrings", typeof(MainStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have questions about Hellolingo? Ask the community or the admin in this room..
        /// </summary>
        public static string AboutHellolingoDescription {
            get {
                return ResourceManager.GetString("AboutHellolingoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Hellolingo.
        /// </summary>
        public static string AboutHellolingoTitle {
            get {
                return ResourceManager.GetString("AboutHellolingoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member has been added to your contact list.
        /// </summary>
        public static string AddedToContactsMsg {
            get {
                return ResourceManager.GetString("AddedToContactsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced options for finding partners.
        /// </summary>
        public static string AdvancedFindDescription {
            get {
                return ResourceManager.GetString("AdvancedFindDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find++.
        /// </summary>
        public static string AdvancedFindTitle {
            get {
                return ResourceManager.GetString("AdvancedFindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Features.
        /// </summary>
        public static string AllFeatures {
            get {
                return ResourceManager.GetString("AllFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An App for your Android device.
        /// </summary>
        public static string AndroidAppDescription {
            get {
                return ResourceManager.GetString("AndroidAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Android.
        /// </summary>
        public static string AndroidAppTitle {
            get {
                return ResourceManager.GetString("AndroidAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back in time, any time. Read past conversations and more..
        /// </summary>
        public static string ChatHistoryDescription {
            get {
                return ResourceManager.GetString("ChatHistoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your preferred members to your contacts by using the &lt;span class=&quot;pin-icon&quot;&gt;&lt;/span&gt; button in their profiles..
        /// </summary>
        public static string ContactsWidgetAddMembers {
            get {
                return ResourceManager.GetString("ContactsWidgetAddMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well! Could you try that again?.
        /// </summary>
        public static string CouldYouTryThatAgain {
            get {
                return ResourceManager.GetString("CouldYouTryThatAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already in use..
        /// </summary>
        public static string EmailInUse {
            get {
                return ResourceManager.GetString("EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure all your entries are valid..
        /// </summary>
        public static string EntriesAreInvalid {
            get {
                return ResourceManager.GetString("EntriesAreInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect with your favorite Livemocha members.
        /// </summary>
        public static string FindByLivemochaDescription {
            get {
                return ResourceManager.GetString("FindByLivemochaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livemocha Members.
        /// </summary>
        public static string FindByLivemochaTitle {
            get {
                return ResourceManager.GetString("FindByLivemochaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect with your favorite SharedTalk members.
        /// </summary>
        public static string FindBySharedTalkDescription {
            get {
                return ResourceManager.GetString("FindBySharedTalkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharedTalk Members.
        /// </summary>
        public static string FindBySharedTalkTitle {
            get {
                return ResourceManager.GetString("FindBySharedTalkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the perfect partner for your language exchange.
        /// </summary>
        public static string FindDescription {
            get {
                return ResourceManager.GetString("FindDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Language Partner.
        /// </summary>
        public static string FindTitle {
            get {
                return ResourceManager.GetString("FindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future.
        /// </summary>
        public static string Future {
            get {
                return ResourceManager.GetString("Future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games… You get it, right?.
        /// </summary>
        public static string GamesDescription {
            get {
                return ResourceManager.GetString("GamesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re actively building new &lt;strong&gt;Tools and Features&lt;/strong&gt; for your learning adventure..
        /// </summary>
        public static string HeaderTileDescription {
            get {
                return ResourceManager.GetString("HeaderTileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hellolingo has been updated. Please refresh your page to get the latest version..
        /// </summary>
        public static string HellolingoUpdated {
            get {
                return ResourceManager.GetString("HellolingoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hellolingo, in your language.
        /// </summary>
        public static string I18NDescription {
            get {
                return ResourceManager.GetString("I18NDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In your language.
        /// </summary>
        public static string I18NTitle {
            get {
                return ResourceManager.GetString("I18NTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password..
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And App for your Apple device.
        /// </summary>
        public static string IosAppDescription {
            get {
                return ResourceManager.GetString("IosAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On iPhone.
        /// </summary>
        public static string IosAppTitle {
            get {
                return ResourceManager.GetString("IosAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn new skills from a large set of content and resources.
        /// </summary>
        public static string LearningContentDescription {
            get {
                return ResourceManager.GetString("LearningContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Content.
        /// </summary>
        public static string LearningContentTitle {
            get {
                return ResourceManager.GetString("LearningContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read and manage your mail, reply by email to your partners.
        /// </summary>
        public static string MailboxDescription {
            get {
                return ResourceManager.GetString("MailboxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simultaneous chat windows for your large screen.
        /// </summary>
        public static string ModularChatDescription {
            get {
                return ResourceManager.GetString("ModularChatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modular Chat.
        /// </summary>
        public static string ModularChatTitle {
            get {
                return ResourceManager.GetString("ModularChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Features.
        /// </summary>
        public static string MoreFeaturesTitle {
            get {
                return ResourceManager.GetString("MoreFeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Mailbox.
        /// </summary>
        public static string MyMailbox {
            get {
                return ResourceManager.GetString("MyMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message.
        /// </summary>
        public static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404! :-/.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this member to your contact list.
        /// </summary>
        public static string PinButtonTitle {
            get {
                return ResourceManager.GetString("PinButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin your preferred features to the top of the screen..
        /// </summary>
        public static string PinYourFeatures {
            get {
                return ResourceManager.GetString("PinYourFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Chat.
        /// </summary>
        public static string PrivateChat {
            get {
                return ResourceManager.GetString("PrivateChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage, edit and make your profile even more awesome.
        /// </summary>
        public static string ProfileDescription {
            get {
                return ResourceManager.GetString("ProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a stronger password..
        /// </summary>
        public static string ProvideStrongerPassword {
            get {
                return ResourceManager.GetString("ProvideStrongerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member has been removed from your contact list.
        /// </summary>
        public static string RemovedFromContactsMsg {
            get {
                return ResourceManager.GetString("RemovedFromContactsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the community to review your text. You’ll learn quite a few tricks..
        /// </summary>
        public static string ReviewAndEditDescription {
            get {
                return ResourceManager.GetString("ReviewAndEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews &amp; Edit.
        /// </summary>
        public static string ReviewAndEditTitle {
            get {
                return ResourceManager.GetString("ReviewAndEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That one will open a whole new world of opportunities.
        /// </summary>
        public static string SecretTool1Description {
            get {
                return ResourceManager.GetString("SecretTool1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Tool #1.
        /// </summary>
        public static string SecretTool1Title {
            get {
                return ResourceManager.GetString("SecretTool1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This one will make your life so much easier.
        /// </summary>
        public static string SecretTool2Description {
            get {
                return ResourceManager.GetString("SecretTool2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Tool #2.
        /// </summary>
        public static string SecretTool2Title {
            get {
                return ResourceManager.GetString("SecretTool2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharedLingo.
        /// </summary>
        public static string SharedLingo {
            get {
                return ResourceManager.GetString("SharedLingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy a fun conversation with other learners.
        /// </summary>
        public static string TextChatDescription {
            get {
                return ResourceManager.GetString("TextChatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text &amp; Voice Chat.
        /// </summary>
        public static string TextChatTitle {
            get {
                return ResourceManager.GetString("TextChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your email and password..
        /// </summary>
        public static string VerifyPassword {
            get {
                return ResourceManager.GetString("VerifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Chat.
        /// </summary>
        public static string ViewChat {
            get {
                return ResourceManager.GetString("ViewChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Call.
        /// </summary>
        public static string VoiceCall {
            get {
                return ResourceManager.GetString("VoiceCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A more powerful and more flexible voice chat that adapts to your needs.
        /// </summary>
        public static string VoiceOutDescription {
            get {
                return ResourceManager.GetString("VoiceOutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Chat++.
        /// </summary>
        public static string VoiceOutTitle {
            get {
                return ResourceManager.GetString("VoiceOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contacts.
        /// </summary>
        public static string YourContactListTitle {
            get {
                return ResourceManager.GetString("YourContactListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decide which new features we build for you next.
        /// </summary>
        public static string YourFeaturesDescription {
            get {
                return ResourceManager.GetString("YourFeaturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your features.
        /// </summary>
        public static string YourFeaturesTitle {
            get {
                return ResourceManager.GetString("YourFeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw your ideas of new features and games for Hellolingo.
        /// </summary>
        public static string YourMockupsDescription {
            get {
                return ResourceManager.GetString("YourMockupsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ideas.
        /// </summary>
        public static string YourMockupsTitle {
            get {
                return ResourceManager.GetString("YourMockupsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore online language learning resources and vote for the ones you like the most.
        /// </summary>
        public static string YourResourcesDescription {
            get {
                return ResourceManager.GetString("YourResourcesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your resources.
        /// </summary>
        public static string YourResourcesTitle {
            get {
                return ResourceManager.GetString("YourResourcesTitle", resourceCulture);
            }
        }
    }
}
