//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageTitleResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageTitleResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Considerate.Hellolingo.I18N.PageTitleResource", typeof(PageTitleResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find other awesome members by languages.
        /// </summary>
        public static string PageTitle_FindByLanguages {
            get {
                return ResourceManager.GetString("PageTitle_FindByLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find former Livemocha members.
        /// </summary>
        public static string PageTitle_FindByLivemocha {
            get {
                return ResourceManager.GetString("PageTitle_FindByLivemocha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find other members by name.
        /// </summary>
        public static string PageTitle_FindByName {
            get {
                return ResourceManager.GetString("PageTitle_FindByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find former SharedTalk members.
        /// </summary>
        public static string PageTitle_FindBySharedTalk {
            get {
                return ResourceManager.GetString("PageTitle_FindBySharedTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Chat Lobby.
        /// </summary>
        public static string PageTitle_TextChatLobby {
            get {
                return ResourceManager.GetString("PageTitle_TextChatLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invitations.
        /// </summary>
        public static string PageTitle_TextChatRoomInvitations {
            get {
                return ResourceManager.GetString("PageTitle_TextChatRoomInvitations", resourceCulture);
            }
        }
    }
}
