//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsFoundation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsFoundation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Considerate.Hellolingo.I18N.StringsFoundation", typeof(StringsFoundation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Activation.
        /// </summary>
        public static string AccountActivation {
            get {
                return ResourceManager.GetString("AccountActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been verified successfully..
        /// </summary>
        public static string AccountHasBeenVerified {
            get {
                return ResourceManager.GetString("AccountHasBeenVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Members.
        /// </summary>
        public static string ActiveMembers {
            get {
                return ResourceManager.GetString("ActiveMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and more....
        /// </summary>
        public static string AndMore {
            get {
                return ResourceManager.GetString("AndMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A New Language&lt;br /&gt;Exchange Community.
        /// </summary>
        public static string ANewLanguageCommunity {
            get {
                return ResourceManager.GetString("ANewLanguageCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ready?.
        /// </summary>
        public static string AreYouReady {
            get {
                return ResourceManager.GetString("AreYouReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to log out?.
        /// </summary>
        public static string AreYouSureYouWantToLogOut {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome&lt;br/&gt;Members.
        /// </summary>
        public static string AwesomeMembers {
            get {
                return ResourceManager.GetString("AwesomeMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a member, it&apos;s FREE!.
        /// </summary>
        public static string BecomeAMemberItsFree {
            get {
                return ResourceManager.GetString("BecomeAMemberItsFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born in....
        /// </summary>
        public static string BornIn {
            get {
                return ResourceManager.GetString("BornIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A community built by its members..
        /// </summary>
        public static string BuiltByMembers {
            get {
                return ResourceManager.GetString("BuiltByMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out our members.
        /// </summary>
        public static string CheckOutOurMembers {
            get {
                return ResourceManager.GetString("CheckOutOurMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &apos;Save&apos;, you agree and consent to our {0}Terms of use, including our Cookie Use and Privacy Policy{1}..
        /// </summary>
        public static string ClickMeansAgreeWithTerms {
            get {
                return ResourceManager.GetString("ClickMeansAgreeWithTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by clicking &lt;a href=&quot;#EmailConfirmationUrl#&quot;&gt;this link&lt;/a&gt;..
        /// </summary>
        public static string ConfirmYourAccountByClickingHere {
            get {
                return ResourceManager.GetString("ConfirmYourAccountByClickingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for information.
        /// </summary>
        public static string ContactOption_AskInformation {
            get {
                return ResourceManager.GetString("ContactOption_AskInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Subject.
        /// </summary>
        public static string ContactOption_OtherSubject {
            get {
                return ResourceManager.GetString("ContactOption_OtherSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Feedback.
        /// </summary>
        public static string ContactOption_ProvideFeedback {
            get {
                return ResourceManager.GetString("ContactOption_ProvideFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Abuse.
        /// </summary>
        public static string ContactOption_ReportAbuse {
            get {
                return ResourceManager.GetString("ContactOption_ReportAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a Bug.
        /// </summary>
        public static string ContactOption_ReportBug {
            get {
                return ResourceManager.GetString("ContactOption_ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a new feature.
        /// </summary>
        public static string ContactOption_RequestNewFeature {
            get {
                return ResourceManager.GetString("ContactOption_RequestNewFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Copyright 1985-2017 Considerate LLC. All Rights Reserved.
        /// </summary>
        public static string CopyrightLine {
            get {
                return ResourceManager.GetString("CopyrightLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Manager.
        /// </summary>
        public static string CreativeManager {
            get {
                return ResourceManager.GetString("CreativeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re going to definitely delete your account and all your emails. Are you sure you want to do this?.
        /// </summary>
        public static string DeleteAccountWarning {
            get {
                return ResourceManager.GetString("DeleteAccountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete my profile.
        /// </summary>
        public static string DeleteMyProfile {
            get {
                return ResourceManager.GetString("DeleteMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover and share the best resources. Connect with learners, practise with speakers..
        /// </summary>
        public static string DiscoverAndShare {
            get {
                return ResourceManager.GetString("DiscoverAndShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your email address.
        /// </summary>
        public static string EditYourEmailAddress {
            get {
                return ResourceManager.GetString("EditYourEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already signed up. Please log in instead..
        /// </summary>
        public static string EmailAlreadySignedIn {
            get {
                return ResourceManager.GetString("EmailAlreadySignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent.
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email with instructions to reset your password has been sent to your email address.
        /// </summary>
        public static string EmailWithPasswordResetInfoSentMsg {
            get {
                return ResourceManager.GetString("EmailWithPasswordResetInfoSentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your current password to confirm your changes.
        /// </summary>
        public static string EnterCurrentPasswordToConfirm {
            get {
                return ResourceManager.GetString("EnterCurrentPasswordToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t verify your email address..
        /// </summary>
        public static string FailedToVerifyYourEmail {
            get {
                return ResourceManager.GetString("FailedToVerifyYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form incomplete or incorrect.
        /// </summary>
        public static string FormIncompleteOrIncorrect {
            get {
                return ResourceManager.GetString("FormIncompleteOrIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founder and Developer.
        /// </summary>
        public static string FounderAndDeveloper {
            get {
                return ResourceManager.GetString("FounderAndDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From....
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You practise with a &lt;B&gt;native speaker&lt;/B&gt;..
        /// </summary>
        public static string Goals1 {
            get {
                return ResourceManager.GetString("Goals1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You discover other &lt;B&gt;cultures and ways of life&lt;/B&gt;..
        /// </summary>
        public static string Goals2 {
            get {
                return ResourceManager.GetString("Goals2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can share &lt;B&gt;hobbies and interests&lt;/B&gt; with your language partners..
        /// </summary>
        public static string Goals3 {
            get {
                return ResourceManager.GetString("Goals3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are more likely to learn &lt;B&gt;slang and informal expressions&lt;/B&gt; than in a classroom or in a book..
        /// </summary>
        public static string Goals4 {
            get {
                return ResourceManager.GetString("Goals4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can easily ask your language partners for &lt;B&gt;explanations&lt;/B&gt; about vocabulary and grammar..
        /// </summary>
        public static string Goals5 {
            get {
                return ResourceManager.GetString("Goals5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A language exchange is the &lt;b&gt;best method&lt;/b&gt; to improve your language skills and become more fluent than ever..
        /// </summary>
        public static string Goals6 {
            get {
                return ResourceManager.GetString("Goals6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on....
        /// </summary>
        public static string HellolingoBasedOn {
            get {
                return ResourceManager.GetString("HellolingoBasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi #FirstName#!.
        /// </summary>
        public static string HiFirstName {
            get {
                return ResourceManager.GetString("HiFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can we help you?.
        /// </summary>
        public static string HowCanWeHelpYou {
            get {
                return ResourceManager.GetString("HowCanWeHelpYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can you help?.
        /// </summary>
        public static string HowCanYouHelp {
            get {
                return ResourceManager.GetString("HowCanYouHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m....
        /// </summary>
        public static string IAm {
            get {
                return ResourceManager.GetString("IAm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I double-checked that my email address is correct.
        /// </summary>
        public static string IDoubleCheckedEmail {
            get {
                return ResourceManager.GetString("IDoubleCheckedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m a former....
        /// </summary>
        public static string ImFormer {
            get {
                return ResourceManager.GetString("ImFormer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m learning....
        /// </summary>
        public static string ImLearning {
            get {
                return ResourceManager.GetString("ImLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m looking to learn with....
        /// </summary>
        public static string ImLookingToLearn {
            get {
                return ResourceManager.GetString("ImLookingToLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...in just a few clicks.
        /// </summary>
        public static string InFewClicks {
            get {
                return ResourceManager.GetString("InFewClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite your language partners,&lt;br&gt;your friends, your family!.
        /// </summary>
        public static string InviteYourPartnersAndAll {
            get {
                return ResourceManager.GetString("InviteYourPartnersAndAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is learning.
        /// </summary>
        public static string IsLearning {
            get {
                return ResourceManager.GetString("IsLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Us!.
        /// </summary>
        public static string JoinUs {
            get {
                return ResourceManager.GetString("JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members who are learning #learn# and who know #know#.
        /// </summary>
        public static string LanguagesFilterLine {
            get {
                return ResourceManager.GetString("LanguagesFilterLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Livemocha&lt;/strong&gt; was a large community-based language learning website. It was closed in 2016, much to the disappointment of its 10+ millions users. With Hellolingo, we want to provide former Livemocha members with new opportunities to learn foreign languages..
        /// </summary>
        public static string LivemochaInfo {
            get {
                return ResourceManager.GetString("LivemochaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Livemocha&lt;/strong&gt; member.
        /// </summary>
        public static string LivemochaMember {
            get {
                return ResourceManager.GetString("LivemochaMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made in....
        /// </summary>
        public static string MadeIn {
            get {
                return ResourceManager.GetString("MadeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members who are learning....
        /// </summary>
        public static string MembersLearn {
            get {
                return ResourceManager.GetString("MembersLearn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members who speak....
        /// </summary>
        public static string MembersSpeak {
            get {
                return ResourceManager.GetString("MembersSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile-Friendly.
        /// </summary>
        public static string MobileFriendly {
            get {
                return ResourceManager.GetString("MobileFriendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern Design.
        /// </summary>
        public static string ModernDesign {
            get {
                return ResourceManager.GetString("ModernDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about myself.
        /// </summary>
        public static string MoreAboutMyself {
            get {
                return ResourceManager.GetString("MoreAboutMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The more people interested,&lt;br&gt;the more we build it!.
        /// </summary>
        public static string MorePeopleMoreFeatures {
            get {
                return ResourceManager.GetString("MorePeopleMoreFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My native language is....
        /// </summary>
        public static string MyNativeIs {
            get {
                return ResourceManager.GetString("MyNativeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a member yet?.
        /// </summary>
        public static string NotMemberYet {
            get {
                return ResourceManager.GetString("NotMemberYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        public static string OopsTryAgainLater {
            get {
                return ResourceManager.GetString("OopsTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Language Exchange Starts Here - Hellolingo.
        /// </summary>
        public static string PageTitle_Home {
            get {
                return ResourceManager.GetString("PageTitle_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livemocha lives again.
        /// </summary>
        public static string PageTitle_Livemocha {
            get {
                return ResourceManager.GetString("PageTitle_Livemocha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharedLingo joins Hellolingo!.
        /// </summary>
        public static string PageTitle_SharedLingo {
            get {
                return ResourceManager.GetString("PageTitle_SharedLingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharedTalk lives again!.
        /// </summary>
        public static string PageTitle_SharedTalk {
            get {
                return ResourceManager.GetString("PageTitle_SharedTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password must contain 6 to 99 characters..
        /// </summary>
        public static string PasswordLengthErrorMsg {
            get {
                return ResourceManager.GetString("PasswordLengthErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your passwords don&apos;t match.
        /// </summary>
        public static string PasswordsDifferMsg {
            get {
                return ResourceManager.GetString("PasswordsDifferMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Please confirm your email address.&lt;/h4&gt; An email has been sent to you at {{email}}. Check your mailbox and follow the instructions.&lt;h6&gt;Make sure to check your spam folder and allow emails from hello@hellolingo.com&lt;/h6&gt;.
        /// </summary>
        public static string PleaseConfirmYourAccountMsg {
            get {
                return ResourceManager.GetString("PleaseConfirmYourAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated successfully..
        /// </summary>
        public static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend confirmation email.
        /// </summary>
        public static string ResendConfirmationEmail {
            get {
                return ResourceManager.GetString("ResendConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Password.
        /// </summary>
        public static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right here! Right now!.
        /// </summary>
        public static string RightHereNow {
            get {
                return ResourceManager.GetString("RightHereNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;SharedLingo&lt;/strong&gt; member.
        /// </summary>
        public static string SharedLingoMember {
            get {
                return ResourceManager.GetString("SharedLingoMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;&lt;a href=&quot;/sharedtalk&quot;&gt;SharedTalk&lt;/a&gt;&lt;/strong&gt; was a free Language Exchange community of 1.5 millions members, closed after 10 years of activity by its new owner in 2015. The original founder of SharedTalk has created Hellolingo to bring back all the SharedTalk goodness and allow its members to keep practicing and stay connected with their language partners..
        /// </summary>
        public static string SharedTalkInfo {
            get {
                return ResourceManager.GetString("SharedTalkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;SharedTalk&lt;/strong&gt; member.
        /// </summary>
        public static string SharedTalkMember {
            get {
                return ResourceManager.GetString("SharedTalkMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each registration is verified and rejected if incorrect, inconsistent or inappropriate..
        /// </summary>
        public static string SignupCheckWarning {
            get {
                return ResourceManager.GetString("SignupCheckWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Engineer and Linguistics Expert.
        /// </summary>
        public static string SoftwareAndLinguistics {
            get {
                return ResourceManager.GetString("SoftwareAndLinguistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaks.
        /// </summary>
        public static string Speaks {
            get {
                return ResourceManager.GetString("Speaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread the word!.
        /// </summary>
        public static string SpreadTheWord {
            get {
                return ResourceManager.GetString("SpreadTheWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superior&lt;br/&gt;Experience.
        /// </summary>
        public static string SuperiorExperience {
            get {
                return ResourceManager.GetString("SuperiorExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us something about yourself : hobbies, studies, interests, why you are learning languages....
        /// </summary>
        public static string TellMoreToTheCommunity {
            get {
                return ResourceManager.GetString("TellMoreToTheCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Chat.
        /// </summary>
        public static string TextChat {
            get {
                return ResourceManager.GetString("TextChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hellolingo in [LANG] is made possible thanks to our members and friends..
        /// </summary>
        public static string UICultureChangeCredits {
            get {
                return ResourceManager.GetString("UICultureChangeCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this time, about 50% of Hellolingo is in [LANG]. We&apos;ll display text that hasn&apos;t been translated yet in English. Don&apos;t hesitate to contact us if you want to help complete the [LANG] version of Hellolingo..
        /// </summary>
        public static string UICultureChangeHelpUs {
            get {
                return ResourceManager.GetString("UICultureChangeHelpUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find this email address.
        /// </summary>
        public static string UnableToFindEmail {
            get {
                return ResourceManager.GetString("UnableToFindEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Chat.
        /// </summary>
        public static string VoiceChat {
            get {
                return ResourceManager.GetString("VoiceChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to help build Hellolingo.
        /// </summary>
        public static string WantToHelp {
            get {
                return ResourceManager.GetString("WantToHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warmest regards from the Hellolingo community.
        /// </summary>
        public static string WarmestRegardsFromHellolingoCommunity {
            get {
                return ResourceManager.GetString("WarmestRegardsFromHellolingoCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re building it!.
        /// </summary>
        public static string WeAreBuildingIt {
            get {
                return ResourceManager.GetString("WeAreBuildingIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re building a community for your Language Learning..
        /// </summary>
        public static string WeBuildingCommunityForYou {
            get {
                return ResourceManager.GetString("WeBuildingCommunityForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Hellolingo!.
        /// </summary>
        public static string WelcomeToHellolingo {
            get {
                return ResourceManager.GetString("WelcomeToHellolingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With &lt;a href=&quot;https://en.wikipedia.org/wiki/Language_exchange&quot; class=&quot;lang-xchg-link&quot; target=&quot;_blank&quot;&gt;Language Exchange&lt;/a&gt;, you can harness the power of social networking and the endless resources of the web....
        /// </summary>
        public static string WithLanguageExchangeYouGotItAll {
            get {
                return ResourceManager.GetString("WithLanguageExchangeYouGotItAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Many Advantages.
        /// </summary>
        public static string WithManyAdvantages {
            get {
                return ResourceManager.GetString("WithManyAdvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
    }
}
