//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextChatResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextChatResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Considerate.Hellolingo.I18N.TextChatResource", typeof(TextChatResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already started an audio conversation with another member.
        /// </summary>
        public static string Audio_Busy {
            get {
                return ResourceManager.GetString("Audio_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received a call, but you already started an audio conversation with another member..
        /// </summary>
        public static string Audio_Decline_Busy {
            get {
                return ResourceManager.GetString("Audio_Decline_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received a call, but your browser doesn&apos;t support voice chat..
        /// </summary>
        public static string Audio_Decline_Unsupported_Browser {
            get {
                return ResourceManager.GetString("Audio_Decline_Unsupported_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received a call, but your device microphone was unavailable.
        /// </summary>
        public static string Audio_Decline_Unsupported_Device {
            get {
                return ResourceManager.GetString("Audio_Decline_Unsupported_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voice chat has ended..
        /// </summary>
        public static string Audio_Hangout {
            get {
                return ResourceManager.GetString("Audio_Hangout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your partner is already having a voice call..
        /// </summary>
        public static string Audio_Peer_Busy {
            get {
                return ResourceManager.GetString("Audio_Peer_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your call has been declined..
        /// </summary>
        public static string Audio_Peer_Declined {
            get {
                return ResourceManager.GetString("Audio_Peer_Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your partner has ended the call..
        /// </summary>
        public static string Audio_Peer_Hangout {
            get {
                return ResourceManager.GetString("Audio_Peer_Hangout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your partner&apos;s device doesn&apos;t support voice chat..
        /// </summary>
        public static string Audio_Peer_Unsupported {
            get {
                return ResourceManager.GetString("Audio_Peer_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser doesn&apos;t support voice chat..
        /// </summary>
        public static string Audio_Unsupported_Browser {
            get {
                return ResourceManager.GetString("Audio_Unsupported_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device microphone is not available.
        /// </summary>
        public static string Audio_Unsupported_Device {
            get {
                return ResourceManager.GetString("Audio_Unsupported_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already calling this member from another session..
        /// </summary>
        public static string Audio_Unsupported_Join {
            get {
                return ResourceManager.GetString("Audio_Unsupported_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re connected.
        /// </summary>
        public static string Audio_YoureConnected {
            get {
                return ResourceManager.GetString("Audio_YoureConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invitation has been sent to the member..
        /// </summary>
        public static string CallHasBeenSent {
            get {
                return ResourceManager.GetString("CallHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling....
        /// </summary>
        public static string Calling {
            get {
                return ResourceManager.GetString("Calling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat History.
        /// </summary>
        public static string ChatHistory {
            get {
                return ResourceManager.GetString("ChatHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your chat history preserves all your conversations with other members. You can invite members to private conversations from the &lt;a href=&quot;/text-chat/lobby&quot;&gt;list of online members.&lt;/a&gt;.
        /// </summary>
        public static string ChatHistoryHint {
            get {
                return ResourceManager.GetString("ChatHistoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Request.
        /// </summary>
        public static string ChatRequest {
            get {
                return ResourceManager.GetString("ChatRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been disconnected due to inactivity..
        /// </summary>
        public static string DisconnectedInactivity {
            get {
                return ResourceManager.GetString("DisconnectedInactivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redock.
        /// </summary>
        public static string Dock {
            get {
                return ResourceManager.GetString("Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your room name here.
        /// </summary>
        public static string EnterSecretRoom {
            get {
                return ResourceManager.GetString("EnterSecretRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Hellolingo room! If you have questions or requests about Hellolingo, this is the right place for you. Get answers from the community and the Hellolingo creators. Let&apos;s build a better learning community together..
        /// </summary>
        public static string FirstMessage {
            get {
                return ResourceManager.GetString("FirstMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hang up.
        /// </summary>
        public static string HangUp {
            get {
                return ResourceManager.GetString("HangUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Accepted.
        /// </summary>
        public static string InvitationAccepted {
            get {
                return ResourceManager.GetString("InvitationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been invited to private chat..
        /// </summary>
        public static string InvitedToPrivateChat {
            get {
                return ResourceManager.GetString("InvitedToPrivateChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Recently.
        /// </summary>
        public static string JustLeft {
            get {
                return ResourceManager.GetString("JustLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave this room.
        /// </summary>
        public static string LeaveRoom {
            get {
                return ResourceManager.GetString("LeaveRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! This member prefers not to receive private chat invitations.
        /// </summary>
        public static string MemberDoesntWantPrivate {
            get {
                return ResourceManager.GetString("MemberDoesntWantPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This member prefers not to receive private chat invitations but is present in the following chat rooms:.
        /// </summary>
        public static string MemberDoesntWantPrivateButIsInPublicRoom {
            get {
                return ResourceManager.GetString("MemberDoesntWantPrivateButIsInPublicRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More learners....
        /// </summary>
        public static string MoreLearners {
            get {
                return ResourceManager.GetString("MoreLearners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute this member.
        /// </summary>
        public static string MuteButtonTitle {
            get {
                return ResourceManager.GetString("MuteButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message received. Click to see!.
        /// </summary>
        public static string NewMessageReceived {
            get {
                return ResourceManager.GetString("NewMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Members.
        /// </summary>
        public static string OnlineMembers {
            get {
                return ResourceManager.GetString("OnlineMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your partner wants to start a voice chat.
        /// </summary>
        public static string PartnerWantsToStartVoice {
            get {
                return ResourceManager.GetString("PartnerWantsToStartVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Chats.
        /// </summary>
        public static string PrivateChats {
            get {
                return ResourceManager.GetString("PrivateChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Chat Rooms.
        /// </summary>
        public static string PublicChatRooms {
            get {
                return ResourceManager.GetString("PublicChatRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chat room will open as soon as he/she accepts the invitation..
        /// </summary>
        public static string RoomWillOpenWhenAccepted {
            get {
                return ResourceManager.GetString("RoomWillOpenWhenAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Say &apos;Hi!&apos; or write your message here).
        /// </summary>
        public static string SayHi {
            get {
                return ResourceManager.GetString("SayHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Rooms.
        /// </summary>
        public static string SecretRooms {
            get {
                return ResourceManager.GetString("SecretRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write and send a message to invite this member to a private conversation..
        /// </summary>
        public static string SendMessageToStart {
            get {
                return ResourceManager.GetString("SendMessageToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio notification of new messages.
        /// </summary>
        public static string Settings_AudioNotificationsOfNewMessages {
            get {
                return ResourceManager.GetString("Settings_AudioNotificationsOfNewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive private chat invitations.
        /// </summary>
        public static string Settings_ReceivePrivateChatInvitations {
            get {
                return ResourceManager.GetString("Settings_ReceivePrivateChatInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share your email address.
        /// </summary>
        public static string ShareEmail {
            get {
                return ResourceManager.GetString("ShareEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share a secret room.
        /// </summary>
        public static string ShareSecretRoom {
            get {
                return ResourceManager.GetString("ShareSecretRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share your Skype.
        /// </summary>
        public static string ShareSkype {
            get {
                return ResourceManager.GetString("ShareSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll no longer receive chat messages or invitations from this member.
        /// </summary>
        public static string TheMemberHasBeenMuted {
            get {
                return ResourceManager.GetString("TheMemberHasBeenMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member has been unmuted.
        /// </summary>
        public static string TheMemberHasBeenUnmuted {
            get {
                return ResourceManager.GetString("TheMemberHasBeenUnmuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This member wants to start a private chat with you..
        /// </summary>
        public static string ThisMemberWantsToChat {
            get {
                return ResourceManager.GetString("ThisMemberWantsToChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is invalid.
        /// </summary>
        public static string ToolTipsEmailInvalid {
            get {
                return ResourceManager.GetString("ToolTipsEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        public static string ToolTipsErrorTitle {
            get {
                return ResourceManager.GetString("ToolTipsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with Skype.
        /// </summary>
        public static string ToolTipsOpenWithSkype {
            get {
                return ResourceManager.GetString("ToolTipsOpenWithSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room name must have 6 to 20 letters or digits.
        /// </summary>
        public static string ToolTipsSecretRoomInvalid {
            get {
                return ResourceManager.GetString("ToolTipsSecretRoomInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string ToolTipsSendEmail {
            get {
                return ResourceManager.GetString("ToolTipsSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A language exchange network, closed since September 2015.
        /// </summary>
        public static string ToolTipsSharedTalk {
            get {
                return ResourceManager.GetString("ToolTipsSharedTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string ToolTipsSkype {
            get {
                return ResourceManager.GetString("ToolTipsSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Skype id is invalid.
        /// </summary>
        public static string ToolTipsSkypeInvalid {
            get {
                return ResourceManager.GetString("ToolTipsSkypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        public static string ToolTipsVisit {
            get {
                return ResourceManager.GetString("ToolTipsVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Secret Room.
        /// </summary>
        public static string ToolTipsVisitSecretRoom {
            get {
                return ResourceManager.GetString("ToolTipsVisitSecretRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undock.
        /// </summary>
        public static string Undock {
            get {
                return ResourceManager.GetString("Undock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        public static string ViewProfile {
            get {
                return ResourceManager.GetString("ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your partner is offline.
        /// </summary>
        public static string YourPartnerIsOffline {
            get {
                return ResourceManager.GetString("YourPartnerIsOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your skype here.
        /// </summary>
        public static string YourSkypeId {
            get {
                return ResourceManager.GetString("YourSkypeId", resourceCulture);
            }
        }
    }
}
