//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Considerate.Hellolingo.I18N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VoiceOutResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VoiceOutResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Considerate.Hellolingo.I18N.VoiceOutResource", typeof(VoiceOutResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boost your chances to connect by sharing all the services you use..
        /// </summary>
        public static string BoostYourChances {
            get {
                return ResourceManager.GetString("BoostYourChances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to invite members for a voice chat.
        /// </summary>
        public static string ClickToInvite {
            get {
                return ResourceManager.GetString("ClickToInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact address has been copied to your clipboard.
        /// </summary>
        public static string ContactCopiedToClipBoard {
            get {
                return ResourceManager.GetString("ContactCopiedToClipBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this invitation?.
        /// </summary>
        public static string DeleteInviteConfirm {
            get {
                return ResourceManager.GetString("DeleteInviteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite all the selected members.
        /// </summary>
        public static string InviteAll {
            get {
                return ResourceManager.GetString("InviteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited.
        /// </summary>
        public static string Invited {
            get {
                return ResourceManager.GetString("Invited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inviting Members.
        /// </summary>
        public static string InvitingMembers {
            get {
                return ResourceManager.GetString("InvitingMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The Voice Chat feature allows you to connect with any Hellolingo members, while using your preferred Voice Chat services.&lt;/p&gt;&lt;p&gt;Turn it on to invite others and be invited.&lt;/p&gt;.
        /// </summary>
        public static string LobbyHeadLine {
            get {
                return ResourceManager.GetString("LobbyHeadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Invitations.
        /// </summary>
        public static string NewInvitations {
            get {
                return ResourceManager.GetString("NewInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven’t received an invitation to chat yet..
        /// </summary>
        public static string NoInvitations {
            get {
                return ResourceManager.GetString("NoInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one contact is needed to complete an invitation..
        /// </summary>
        public static string OneContactNeeded {
            get {
                return ResourceManager.GetString("OneContactNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select as many services as you want to use:.
        /// </summary>
        public static string SelectServices {
            get {
                return ResourceManager.GetString("SelectServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the contact information you want to share with your partner(s)..
        /// </summary>
        public static string ShareWithPartners {
            get {
                return ResourceManager.GetString("ShareWithPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try inviting some members!.
        /// </summary>
        public static string TryInvite {
            get {
                return ResourceManager.GetString("TryInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been invited to a voice chat..
        /// </summary>
        public static string YouAreInvited {
            get {
                return ResourceManager.GetString("YouAreInvited", resourceCulture);
            }
        }
    }
}
